# Generated by Django 5.2.15 on 2026-06-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolvedProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('statement', models.TextField()),
                ('solution', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('topic', models.CharField(choices=[('Arrays', 'Arrays'), ('Binary Search', 'Binary Search'), ('Linked List', 'Linked List'), ('Recursion', 'Recursion'), ('Dynamic Programming', 'Dynamic Programming'), ('Stack and Queue', 'Stack and Queue'), ('Sliding Window', 'Sliding Window'), ('Greedy', 'Greedy'), ('Trees', 'Trees'), ('Graphs', 'Graphs'), ('Miscellaneous', 'Miscellaneous')], default='Miscellaneous', max_length=40)),
                ('score', models.FloatField(blank=True, null=True)),
                ('time_complexity', models.CharField(blank=True, max_length=60)),
                ('space_complexity', models.CharField(blank=True, max_length=60)),
                ('summary', models.TextField(blank=True)),
                ('statement_sha', models.CharField(db_index=True, max_length=40, unique=True)),
                ('solved_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-solved_at'],
            },
        ),
    ]
